// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// alt_class
RawVector alt_class(RObject x);
RcppExport SEXP _altrepr_alt_class(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RObject >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(alt_class(x));
    return rcpp_result_gen;
END_RCPP
}
// alt_classname
RObject alt_classname(RObject x);
RcppExport SEXP _altrepr_alt_classname(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RObject >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(alt_classname(x));
    return rcpp_result_gen;
END_RCPP
}
// alt_pkgname
RObject alt_pkgname(RObject x);
RcppExport SEXP _altrepr_alt_pkgname(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RObject >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(alt_pkgname(x));
    return rcpp_result_gen;
END_RCPP
}
// alt_type
RObject alt_type(RObject x);
RcppExport SEXP _altrepr_alt_type(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RObject >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(alt_type(x));
    return rcpp_result_gen;
END_RCPP
}
// is_altrep
LogicalVector is_altrep(RObject x);
RcppExport SEXP _altrepr_is_altrep(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RObject >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(is_altrep(x));
    return rcpp_result_gen;
END_RCPP
}
// altrep_data1
RObject altrep_data1(RObject x);
RcppExport SEXP _altrepr_altrep_data1(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RObject >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(altrep_data1(x));
    return rcpp_result_gen;
END_RCPP
}
// altrep_data2
RObject altrep_data2(RObject x);
RcppExport SEXP _altrepr_altrep_data2(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RObject >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(altrep_data2(x));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_altrepr_alt_class", (DL_FUNC) &_altrepr_alt_class, 1},
    {"_altrepr_alt_classname", (DL_FUNC) &_altrepr_alt_classname, 1},
    {"_altrepr_alt_pkgname", (DL_FUNC) &_altrepr_alt_pkgname, 1},
    {"_altrepr_alt_type", (DL_FUNC) &_altrepr_alt_type, 1},
    {"_altrepr_is_altrep", (DL_FUNC) &_altrepr_is_altrep, 1},
    {"_altrepr_altrep_data1", (DL_FUNC) &_altrepr_altrep_data1, 1},
    {"_altrepr_altrep_data2", (DL_FUNC) &_altrepr_altrep_data2, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_altrepr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
