# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Gets the altrep class of an object.
#'
#' The altrep class is not the same as the name of the class. For that,
#' you can use [alt_classname()]. The altrep class is a [raw] vector whose
#' value uniquely distinguishes the class from other classes. You are unlikely
#' to find much meaning in the actual vector values, but you might find it
#' useful to check if two objects belong to the same class.The other
#' meaningful use of the class is to check its [attributes()], but it is
#' recommended that you instead use the three dedicated wrapper functions for
#' these attributes: [alt_classname()], [alt_pkgname()], and [alt_type()].
#'
#' @return A raw vector uniquely identifying the altrep class of `x`, or `NULL`
#'   if `x` is not an altrep object.
#' @seealso alt_classname alt_pkgname alt_type
alt_class <- function(x) {
    .Call('_altrepr_alt_class', PACKAGE = 'altrepr', x)
}

alt_classname <- function(x) {
    .Call('_altrepr_alt_classname', PACKAGE = 'altrepr', x)
}

alt_pkgname <- function(x) {
    .Call('_altrepr_alt_pkgname', PACKAGE = 'altrepr', x)
}

alt_type <- function(x) {
    .Call('_altrepr_alt_type', PACKAGE = 'altrepr', x)
}

is_altrep <- function(x) {
    .Call('_altrepr_is_altrep', PACKAGE = 'altrepr', x)
}

altrep_data1 <- function(x) {
    .Call('_altrepr_altrep_data1', PACKAGE = 'altrepr', x)
}

altrep_data2 <- function(x) {
    .Call('_altrepr_altrep_data2', PACKAGE = 'altrepr', x)
}

